"""create books table

Revision ID: 167d05b19761
Revises: 2d3e4b874480
Create Date: 2023-02-23 12:20:04.343883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167d05b19761'
down_revision = '2d3e4b874480'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_ibfk_1', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'genders', ['gender_name'], ['books_genders'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_ibfk_1', 'books', 'genders', ['gender_name'], ['books_genders'])
    # ### end Alembic commands ###
