"""create books table

Revision ID: 2d3e4b874480
Revises: 8e1ebc4c5adf
Create Date: 2023-02-23 12:19:17.393655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d3e4b874480'
down_revision = '8e1ebc4c5adf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
