"""create books table

Revision ID: 8e1ebc4c5adf
Revises: 105848d940b7
Create Date: 2023-02-23 11:23:52.756917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1ebc4c5adf'
down_revision = '105848d940b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
