"""create books table

Revision ID: b6580f30ee92
Revises: 105d4d86f7f8
Create Date: 2023-02-23 11:03:44.544586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6580f30ee92'
down_revision = '105d4d86f7f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
