"""create books table

Revision ID: e1d7643b36ac
Revises: 167d05b19761
Create Date: 2023-02-23 13:54:18.104654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d7643b36ac'
down_revision = '167d05b19761'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('books_genres', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_books_genres'), 'genres', ['books_genres'], unique=True)
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=125), nullable=False),
    sa.Column('author', sa.String(length=30), nullable=False),
    sa.Column('genre_name', sa.String(length=30), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['genre_name'], ['genres.books_genres'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_index(op.f('ix_genres_books_genres'), table_name='genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
